{
 "title": "Telkomsel Load Runner Live Monitoring",
 "description": "This dashboard shows live load test metrics provided by JMeter.",
 "tags": [ "Online" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "request",
    "label": "Request",
    "query": "show tag values from \"vugen_stats\" with key = transaction_name;"
   },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "content": "<h3 style=\"text-align: center;\"><em>The following panels show aggregated metrics for <span style=\"color: #00ccff;\"><strong>all requests</strong></span></em></h3>"
  },
  {
   "title": "Overall Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  count(\"response_time\")/$aggregation FROM \"vugen_stats\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT count(\"response_time\") FROM \"vugen_stats\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Succes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vugen_stats",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Status", "operator": "=", "value": "Pass" }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vugen_stats",
     "query": "SELECT count(\"Status\") FROM \"vugen_stats\" WHERE (\"Status\" = 'Fail') AND $timeFilter",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Status", "operator": "=", "value": "Fail" }
     ]
    }
   ]
  },
  {
   "title": "Response TIme",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "transaction_name" ], "type": "tag" }
     ],
     "measurement": "vugen_stats",
     "query": "SELECT mean(\"response_time\") FROM \"autogen\".\"vugen_stats\" WHERE (\"Status\" = 'Pass') AND $timeFilter GROUP BY time($interval), \"transaction_name\"",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Status", "operator": "=", "value": "Pass" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT  count(\"Status\")/$aggregation FROM \"vugen_stats\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time Vs Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Response Time",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT mean(\"response_time\") FROM \"autogen\".\"vugen_stats\" WHERE (\"Status\" = 'Pass') AND $timeFilter GROUP BY time($interval), \"transaction_name\"",
     "select": [
      [
       { "params": [ "startedThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT  count(\"response_time\")/$aggregation FROM \"vugen_stats\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(PassCount) as Pass,count(FailCount) as Fail, (count(PassCount)/(count(PassCount)+count(FailCount))*100) as \"% Passed\", mean(PassCount) as Avg, min(PassCount) as Min, percentile(PassCount, 90) as \"90%\", max(PassCount) as Max from \n(\nselect \"response_time\" as \"PassCount\" from \"vugen_stats\" where \"Status\" = 'Pass'  and $timeFilter),\n(\nselect \"Status\" as \"FailCount\" from \"vugen_stats\" where \"Status\" = 'Fail' and $timeFilter\n)\ngroup by transaction_name fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "transaction_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vugen_stats",
     "query": "select count(Data) as ErrCount from vugen_err where $timeFilter  group by  Transaction_name,ErrDesc",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Fail" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Status", "operator": "=", "value": "Fail" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "content": "<h3 style=\"text-align: center;\"><em>The following panels show request-specific metrics for the request <span style=\"color: #00ccff;\"><strong>\"[[request]]\"</strong></span></em></h3>"
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "errors / s" }
   ],
   "targets": [
    {
     "alias": "Errors per Second",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" }
     ],
     "measurement": "vugen_stats",
     "query": "SELECT count(\"Status\") FROM \"vugen_stats\" WHERE  \"Status\" = 'Fail' AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "transaction_name", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT count(\"response_time\")/$aggregation FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 56 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"Status\") FROM \"vugen_stats\" WHERE  \"Status\" = 'Pass' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT count(\"responseTime\") FROM \"requestsRaw\" WHERE (\"requestName\" =~ /^$request$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vugen_stats",
     "query": "SELECT count(\"Status\") FROM \"vugen_stats\" WHERE  \"Status\" = 'Fail' AND $timeFilter",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Status", "operator": "=", "value": "Fail" },
      { "condition": "AND", "key": "transaction_name", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vugen_stats",
     "query": "SELECT mean(\"response_time\") FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction_name", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "90 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"response_time\", 90) FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "95 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"response_time\", 95) FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "99 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"response_time\", 99) FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT max(\"response_time\") FROM \"vugen_stats\" WHERE \"transaction_name\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  }
 ]
}